stages:
  - test

image: ubuntu:latest

pytest:
  stage: test
  before_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install -yq python3 python3-pip python3-tk graphviz
    - pip3 install -r requirements.txt
  script:
    - pytest --cov tests/
