stages:
  - test

image: ubuntu:latest

pytest:
  stage: test
  script:
    - apt-get update
    - apt-get install -y python3 python3-pip python3-tk graphviz
    - pip3 install -r requirements.txt
    - pytest